jobs:
  - script: >
      pipelineJob('demo') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('Hello') {
                    steps {
                      echo "hello Shoyeb"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
